CREATE DATABASE yourtube;

\connect yourtube;

CREATE TABLE IF NOT EXISTS system_user
(
    id         bigserial PRIMARY KEY,
    name       VARCHAR(50)             NOT NULL UNIQUE,
    created_on TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS video
(
    id             bigserial PRIMARY KEY,
    title          VARCHAR(100)            NOT NULL,
    description    TEXT,
    filename       UUID                    NOT NULL UNIQUE,
    tags           VARCHAR(20)[],
    created_on     TIMESTAMP DEFAULT now() NOT NULL,
    system_user_id BIGINT                  NOT NULL,
    FOREIGN KEY (system_user_id) REFERENCES system_user (id)
);


INSERT INTO system_user (name, created_on)
VALUES ('Music', now()),
       ('Travel World', now()),
       ('Animal lover', now()),
       ('Sport news', now()),
       ('Food vlog', now());

INSERT INTO video (title, description, filename, tags, created_on, system_user_id)
VALUES ('ESCAPE TO ICELAND  Cinematic Travel Film',
        E'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dapibus semper arcu, in dictum dolor ornare id. Proin varius justo diam, vel maximus lacus congue quis. Suspendisse quis augue ex. Quisque risus felis, tincidunt ac facilisis vitae, molestie ac eros. Sed auctor, nibh vitae laoreet ornare, odio lacus pretium dui, eget condimentum libero sem vel ligula. Donec ut semper libero, at vulputate elit. Donec ac rhoncus ex. Nam finibus varius dignissim. Donec venenatis eget massa vel aliquam. Etiam malesuada nisl id finibus faucibus.\n\nAliquam varius, purus ut venenatis porta, nulla sapien sagittis dui, eget vehicula libero risus tincidunt ante. Morbi viverra eleifend ipsum ut pretium. Ut et sapien turpis. Nullam tempor scelerisque libero, a malesuada nulla mollis in. Integer eget orci ac nibh mollis sagittis. Nullam consectetur, sapien tincidunt sollicitudin dictum, sem lacus iaculis velit, sed sagittis sem nisi et ante. Fusce semper quis turpis eu aliquet. Quisque rhoncus faucibus neque, eu rutrum nisl convallis volutpat. Cras non ex ligula. Donec porttitor sagittis tellus, a fermentum nunc tristique nec. Vestibulum molestie vehicula sodales. Proin lobortis lorem ut enim placerat, vel iaculis dolor viverra.\n\nTEAM:\nSam Clark\nLuke James\nMark Thomson',
        '0e2fabfd-d06a-42c5-a985-d73662d3cde0', ARRAY ['travel', 'photography'], '2021-08-24 14:00:00',
        (SELECT id from system_user WHERE name = 'Travel World')),
       ('Follow your heart compass  Cinematic Japan',
        E'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dapibus semper arcu, in dictum dolor ornare id. Proin varius justo diam, vel maximus lacus congue quis. Suspendisse quis augue ex. Quisque risus felis, tincidunt ac facilisis vitae, molestie ac eros. Sed auctor, nibh vitae laoreet ornare, odio lacus pretium dui, eget condimentum libero sem vel ligula. Donec ut semper libero, at vulputate elit. Donec ac rhoncus ex. Nam finibus varius dignissim. Donec venenatis eget massa vel aliquam. Etiam malesuada nisl id finibus faucibus.\n\nAliquam varius, purus ut venenatis porta, nulla sapien sagittis dui, eget vehicula libero risus tincidunt ante. Morbi viverra eleifend ipsum ut pretium. Ut et sapien turpis. Nullam tempor scelerisque libero, a malesuada nulla mollis in. Integer eget orci ac nibh mollis sagittis. Nullam consectetur, sapien tincidunt sollicitudin dictum, sem lacus iaculis velit, sed sagittis sem nisi et ante. Fusce semper quis turpis eu aliquet. Quisque rhoncus faucibus neque, eu rutrum nisl convallis volutpat. Cras non ex ligula. Donec porttitor sagittis tellus, a fermentum nunc tristique nec. Vestibulum molestie vehicula sodales. Proin lobortis lorem ut enim placerat, vel iaculis dolor viverra.\n\nTEAM:\nSam Clark\nLuke James\nMark Thomson',
        '7a930bae-3225-456f-843f-77e2102fe3b0', ARRAY ['travel'], '2021-08-24 14:00:00',
        (SELECT id from system_user WHERE name = 'Travel World')),
       ('High IQ Moments in Sports',
        E'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dapibus semper arcu, in dictum dolor ornare id. Proin varius justo diam, vel maximus lacus congue quis. Suspendisse quis augue ex. Quisque risus felis, tincidunt ac facilisis vitae, molestie ac eros. Sed auctor, nibh vitae laoreet ornare, odio lacus pretium dui, eget condimentum libero sem vel ligula. Donec ut semper libero, at vulputate elit. Donec ac rhoncus ex. Nam finibus varius dignissim. Donec venenatis eget massa vel aliquam. Etiam malesuada nisl id finibus faucibus.\n\nAliquam varius, purus ut venenatis porta, nulla sapien sagittis dui, eget vehicula libero risus tincidunt ante. Morbi viverra eleifend ipsum ut pretium. Ut et sapien turpis. Nullam tempor scelerisque libero, a malesuada nulla mollis in. Integer eget orci ac nibh mollis sagittis. Nullam consectetur, sapien tincidunt sollicitudin dictum, sem lacus iaculis velit, sed sagittis sem nisi et ante. Fusce semper quis turpis eu aliquet. Quisque rhoncus faucibus neque, eu rutrum nisl convallis volutpat. Cras non ex ligula. Donec porttitor sagittis tellus, a fermentum nunc tristique nec. Vestibulum molestie vehicula sodales. Proin lobortis lorem ut enim placerat, vel iaculis dolor viverra.\n\nTEAM:\nSam Clark\nLuke James\nMark Thomson',
        'a222dc8e-60bd-42d9-b4a7-7311743c6b55', ARRAY ['sport', 'football'], '2021-11-24 14:00:00',
        (SELECT id from system_user WHERE name = 'Sport news')),
       ('How to Make a Croissant Stuffed with Chocolate',
        E'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dapibus semper arcu, in dictum dolor ornare id. Proin varius justo diam, vel maximus lacus congue quis. Suspendisse quis augue ex. Quisque risus felis, tincidunt ac facilisis vitae, molestie ac eros. Sed auctor, nibh vitae laoreet ornare, odio lacus pretium dui, eget condimentum libero sem vel ligula. Donec ut semper libero, at vulputate elit. Donec ac rhoncus ex. Nam finibus varius dignissim. Donec venenatis eget massa vel aliquam. Etiam malesuada nisl id finibus faucibus.\n\nAliquam varius, purus ut venenatis porta, nulla sapien sagittis dui, eget vehicula libero risus tincidunt ante. Morbi viverra eleifend ipsum ut pretium. Ut et sapien turpis. Nullam tempor scelerisque libero, a malesuada nulla mollis in. Integer eget orci ac nibh mollis sagittis. Nullam consectetur, sapien tincidunt sollicitudin dictum, sem lacus iaculis velit, sed sagittis sem nisi et ante. Fusce semper quis turpis eu aliquet. Quisque rhoncus faucibus neque, eu rutrum nisl convallis volutpat. Cras non ex ligula. Donec porttitor sagittis tellus, a fermentum nunc tristique nec. Vestibulum molestie vehicula sodales. Proin lobortis lorem ut enim placerat, vel iaculis dolor viverra.\n\nTEAM:\nSam Clark\nLuke James\nMark Thomson',
        'be542a91-66af-413e-b777-966d09bdf106', ARRAY ['food', 'cooking', 'sweets'], '2021-12-24 14:00:00',
        (SELECT id from system_user WHERE name = 'Food vlog')),
       ('Jaime Lorente - Corazón',
        E'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dapibus semper arcu, in dictum dolor ornare id. Proin varius justo diam, vel maximus lacus congue quis. Suspendisse quis augue ex. Quisque risus felis, tincidunt ac facilisis vitae, molestie ac eros. Sed auctor, nibh vitae laoreet ornare, odio lacus pretium dui, eget condimentum libero sem vel ligula. Donec ut semper libero, at vulputate elit. Donec ac rhoncus ex. Nam finibus varius dignissim. Donec venenatis eget massa vel aliquam. Etiam malesuada nisl id finibus faucibus.\n\nAliquam varius, purus ut venenatis porta, nulla sapien sagittis dui, eget vehicula libero risus tincidunt ante. Morbi viverra eleifend ipsum ut pretium. Ut et sapien turpis. Nullam tempor scelerisque libero, a malesuada nulla mollis in. Integer eget orci ac nibh mollis sagittis. Nullam consectetur, sapien tincidunt sollicitudin dictum, sem lacus iaculis velit, sed sagittis sem nisi et ante. Fusce semper quis turpis eu aliquet. Quisque rhoncus faucibus neque, eu rutrum nisl convallis volutpat. Cras non ex ligula. Donec porttitor sagittis tellus, a fermentum nunc tristique nec. Vestibulum molestie vehicula sodales. Proin lobortis lorem ut enim placerat, vel iaculis dolor viverra.\n\nTEAM:\nSam Clark\nLuke James\nMark Thomson',
        '5fa57577-0f46-4098-a9dd-a792ddc9e745', ARRAY ['music'], '2022-01-01 14:00:00',
        (SELECT id from system_user WHERE name = 'Music')),
       ('JAPAN - 4K EPIC Travel VideoDetails',
        E'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dapibus semper arcu, in dictum dolor ornare id. Proin varius justo diam, vel maximus lacus congue quis. Suspendisse quis augue ex. Quisque risus felis, tincidunt ac facilisis vitae, molestie ac eros. Sed auctor, nibh vitae laoreet ornare, odio lacus pretium dui, eget condimentum libero sem vel ligula. Donec ut semper libero, at vulputate elit. Donec ac rhoncus ex. Nam finibus varius dignissim. Donec venenatis eget massa vel aliquam. Etiam malesuada nisl id finibus faucibus.\n\nAliquam varius, purus ut venenatis porta, nulla sapien sagittis dui, eget vehicula libero risus tincidunt ante. Morbi viverra eleifend ipsum ut pretium. Ut et sapien turpis. Nullam tempor scelerisque libero, a malesuada nulla mollis in. Integer eget orci ac nibh mollis sagittis. Nullam consectetur, sapien tincidunt sollicitudin dictum, sem lacus iaculis velit, sed sagittis sem nisi et ante. Fusce semper quis turpis eu aliquet. Quisque rhoncus faucibus neque, eu rutrum nisl convallis volutpat. Cras non ex ligula. Donec porttitor sagittis tellus, a fermentum nunc tristique nec. Vestibulum molestie vehicula sodales. Proin lobortis lorem ut enim placerat, vel iaculis dolor viverra.\n\nTEAM:\nSam Clark\nLuke James\nMark Thomson',
        'c11691cd-05c6-46f2-a439-1796eb9a0b8a', ARRAY ['travel', 'photography'], '2022-01-24 14:00:00',
        (SELECT id from system_user WHERE name = 'Travel World')),
       ('This Adorable Puppy Wouldn’t Stop Smiling in Her Shelter Kennel  The Dodo',
        E'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dapibus semper arcu, in dictum dolor ornare id. Proin varius justo diam, vel maximus lacus congue quis. Suspendisse quis augue ex. Quisque risus felis, tincidunt ac facilisis vitae, molestie ac eros. Sed auctor, nibh vitae laoreet ornare, odio lacus pretium dui, eget condimentum libero sem vel ligula. Donec ut semper libero, at vulputate elit. Donec ac rhoncus ex. Nam finibus varius dignissim. Donec venenatis eget massa vel aliquam. Etiam malesuada nisl id finibus faucibus.\n\nAliquam varius, purus ut venenatis porta, nulla sapien sagittis dui, eget vehicula libero risus tincidunt ante. Morbi viverra eleifend ipsum ut pretium. Ut et sapien turpis. Nullam tempor scelerisque libero, a malesuada nulla mollis in. Integer eget orci ac nibh mollis sagittis. Nullam consectetur, sapien tincidunt sollicitudin dictum, sem lacus iaculis velit, sed sagittis sem nisi et ante. Fusce semper quis turpis eu aliquet. Quisque rhoncus faucibus neque, eu rutrum nisl convallis volutpat. Cras non ex ligula. Donec porttitor sagittis tellus, a fermentum nunc tristique nec. Vestibulum molestie vehicula sodales. Proin lobortis lorem ut enim placerat, vel iaculis dolor viverra.\n\nTEAM:\nSam Clark\nLuke James\nMark Thomson',
        '87ed613b-a8d3-4fad-ace7-403669dd3315', ARRAY ['animals'], '2021-08-14 14:00:00',
        (SELECT id from system_user WHERE name = 'Animal lover')),
       ('EThis Hawaiian Cat Loves Surfing With His Parents  The Dodo',
        E'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dapibus semper arcu, in dictum dolor ornare id. Proin varius justo diam, vel maximus lacus congue quis. Suspendisse quis augue ex. Quisque risus felis, tincidunt ac facilisis vitae, molestie ac eros. Sed auctor, nibh vitae laoreet ornare, odio lacus pretium dui, eget condimentum libero sem vel ligula. Donec ut semper libero, at vulputate elit. Donec ac rhoncus ex. Nam finibus varius dignissim. Donec venenatis eget massa vel aliquam. Etiam malesuada nisl id finibus faucibus.\n\nAliquam varius, purus ut venenatis porta, nulla sapien sagittis dui, eget vehicula libero risus tincidunt ante. Morbi viverra eleifend ipsum ut pretium. Ut et sapien turpis. Nullam tempor scelerisque libero, a malesuada nulla mollis in. Integer eget orci ac nibh mollis sagittis. Nullam consectetur, sapien tincidunt sollicitudin dictum, sem lacus iaculis velit, sed sagittis sem nisi et ante. Fusce semper quis turpis eu aliquet. Quisque rhoncus faucibus neque, eu rutrum nisl convallis volutpat. Cras non ex ligula. Donec porttitor sagittis tellus, a fermentum nunc tristique nec. Vestibulum molestie vehicula sodales. Proin lobortis lorem ut enim placerat, vel iaculis dolor viverra.\n\nTEAM:\nSam Clark\nLuke James\nMark Thomson',
        '6872a737-1cf0-4a1d-af64-440484700657', ARRAY ['animals'], '2021-08-04 14:00:00',
        (SELECT id from system_user WHERE name = 'Animal lover')),
       ('Tiny Donkey Thinks He''s Actually A Dog   The Dodo',
        E'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dapibus semper arcu, in dictum dolor ornare id. Proin varius justo diam, vel maximus lacus congue quis. Suspendisse quis augue ex. Quisque risus felis, tincidunt ac facilisis vitae, molestie ac eros. Sed auctor, nibh vitae laoreet ornare, odio lacus pretium dui, eget condimentum libero sem vel ligula. Donec ut semper libero, at vulputate elit. Donec ac rhoncus ex. Nam finibus varius dignissim. Donec venenatis eget massa vel aliquam. Etiam malesuada nisl id finibus faucibus.\n\nAliquam varius, purus ut venenatis porta, nulla sapien sagittis dui, eget vehicula libero risus tincidunt ante. Morbi viverra eleifend ipsum ut pretium. Ut et sapien turpis. Nullam tempor scelerisque libero, a malesuada nulla mollis in. Integer eget orci ac nibh mollis sagittis. Nullam consectetur, sapien tincidunt sollicitudin dictum, sem lacus iaculis velit, sed sagittis sem nisi et ante. Fusce semper quis turpis eu aliquet. Quisque rhoncus faucibus neque, eu rutrum nisl convallis volutpat. Cras non ex ligula. Donec porttitor sagittis tellus, a fermentum nunc tristique nec. Vestibulum molestie vehicula sodales. Proin lobortis lorem ut enim placerat, vel iaculis dolor viverra.\n\nTEAM:\nSam Clark\nLuke James\nMark Thomson',
        '732e0e0c-11f4-47fc-abbd-9285bd421051', ARRAY ['animals'], '2021-07-24 14:00:00',
        (SELECT id from system_user WHERE name = 'Animal lover')),
       ('Zendaya - Neverland (Official VideoDetails)',
        E'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dapibus semper arcu, in dictum dolor ornare id. Proin varius justo diam, vel maximus lacus congue quis. Suspendisse quis augue ex. Quisque risus felis, tincidunt ac facilisis vitae, molestie ac eros. Sed auctor, nibh vitae laoreet ornare, odio lacus pretium dui, eget condimentum libero sem vel ligula. Donec ut semper libero, at vulputate elit. Donec ac rhoncus ex. Nam finibus varius dignissim. Donec venenatis eget massa vel aliquam. Etiam malesuada nisl id finibus faucibus.\n\nAliquam varius, purus ut venenatis porta, nulla sapien sagittis dui, eget vehicula libero risus tincidunt ante. Morbi viverra eleifend ipsum ut pretium. Ut et sapien turpis. Nullam tempor scelerisque libero, a malesuada nulla mollis in. Integer eget orci ac nibh mollis sagittis. Nullam consectetur, sapien tincidunt sollicitudin dictum, sem lacus iaculis velit, sed sagittis sem nisi et ante. Fusce semper quis turpis eu aliquet. Quisque rhoncus faucibus neque, eu rutrum nisl convallis volutpat. Cras non ex ligula. Donec porttitor sagittis tellus, a fermentum nunc tristique nec. Vestibulum molestie vehicula sodales. Proin lobortis lorem ut enim placerat, vel iaculis dolor viverra.\n\nTEAM:\nSam Clark\nLuke James\nMark Thomson',
        'dc0b47df-4309-47de-ad60-40abf38cd0d5', ARRAY ['music'], '2021-09-24 14:00:00',
        (SELECT id from system_user WHERE name = 'Music'))