/*
 * This file is generated by jOOQ.
 */
package com.example.yourtubebackend.jooq.tables.records;


import com.example.yourtubebackend.jooq.tables.SystemUser;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemUserRecord extends UpdatableRecordImpl<SystemUserRecord> implements Record3<Long, String, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.system_user.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.system_user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.system_user.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.system_user.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.system_user.created_on</code>.
     */
    public void setCreatedOn(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.system_user.created_on</code>.
     */
    public OffsetDateTime getCreatedOn() {
        return (OffsetDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, OffsetDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, OffsetDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SystemUser.SYSTEM_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return SystemUser.SYSTEM_USER.NAME;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return SystemUser.SYSTEM_USER.CREATED_ON;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreatedOn();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreatedOn();
    }

    @Override
    public SystemUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SystemUserRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SystemUserRecord value3(OffsetDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public SystemUserRecord values(Long value1, String value2, OffsetDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SystemUserRecord
     */
    public SystemUserRecord() {
        super(SystemUser.SYSTEM_USER);
    }

    /**
     * Create a detached, initialised SystemUserRecord
     */
    public SystemUserRecord(Long id, String name, OffsetDateTime createdOn) {
        super(SystemUser.SYSTEM_USER);

        setId(id);
        setName(name);
        setCreatedOn(createdOn);
    }
}
