/*
 * This file is generated by jOOQ.
 */
package com.example.yourtubebackend.jooq.tables.records;


import com.example.yourtubebackend.jooq.tables.Video;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VideoRecord extends UpdatableRecordImpl<VideoRecord> implements Record7<Long, String, String, UUID, String[], OffsetDateTime, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.video.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.video.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.video.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.video.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.video.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.video.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.video.filename</code>.
     */
    public void setFilename(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.video.filename</code>.
     */
    public UUID getFilename() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.video.tags</code>.
     */
    public void setTags(String[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.video.tags</code>.
     */
    public String[] getTags() {
        return (String[]) get(4);
    }

    /**
     * Setter for <code>public.video.created_on</code>.
     */
    public void setCreatedOn(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.video.created_on</code>.
     */
    public OffsetDateTime getCreatedOn() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.video.system_user_id</code>.
     */
    public void setSystemUserId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.video.system_user_id</code>.
     */
    public Long getSystemUserId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, UUID, String[], OffsetDateTime, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, UUID, String[], OffsetDateTime, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Video.VIDEO.ID;
    }

    @Override
    public Field<String> field2() {
        return Video.VIDEO.TITLE;
    }

    @Override
    public Field<String> field3() {
        return Video.VIDEO.DESCRIPTION;
    }

    @Override
    public Field<UUID> field4() {
        return Video.VIDEO.FILENAME;
    }

    @Override
    public Field<String[]> field5() {
        return Video.VIDEO.TAGS;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Video.VIDEO.CREATED_ON;
    }

    @Override
    public Field<Long> field7() {
        return Video.VIDEO.SYSTEM_USER_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public UUID component4() {
        return getFilename();
    }

    @Override
    public String[] component5() {
        return getTags();
    }

    @Override
    public OffsetDateTime component6() {
        return getCreatedOn();
    }

    @Override
    public Long component7() {
        return getSystemUserId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public UUID value4() {
        return getFilename();
    }

    @Override
    public String[] value5() {
        return getTags();
    }

    @Override
    public OffsetDateTime value6() {
        return getCreatedOn();
    }

    @Override
    public Long value7() {
        return getSystemUserId();
    }

    @Override
    public VideoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public VideoRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public VideoRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public VideoRecord value4(UUID value) {
        setFilename(value);
        return this;
    }

    @Override
    public VideoRecord value5(String[] value) {
        setTags(value);
        return this;
    }

    @Override
    public VideoRecord value6(OffsetDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public VideoRecord value7(Long value) {
        setSystemUserId(value);
        return this;
    }

    @Override
    public VideoRecord values(Long value1, String value2, String value3, UUID value4, String[] value5, OffsetDateTime value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VideoRecord
     */
    public VideoRecord() {
        super(Video.VIDEO);
    }

    /**
     * Create a detached, initialised VideoRecord
     */
    public VideoRecord(Long id, String title, String description, UUID filename, String[] tags, OffsetDateTime createdOn, Long systemUserId) {
        super(Video.VIDEO);

        setId(id);
        setTitle(title);
        setDescription(description);
        setFilename(filename);
        setTags(tags);
        setCreatedOn(createdOn);
        setSystemUserId(systemUserId);
    }
}
