/*
 * This file is generated by jOOQ.
 */
package com.example.yourtubebackend.jooq.tables;


import com.example.yourtubebackend.jooq.Keys;
import com.example.yourtubebackend.jooq.Public;
import com.example.yourtubebackend.jooq.tables.records.SystemUserRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemUser extends TableImpl<SystemUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.system_user</code>
     */
    public static final SystemUser SYSTEM_USER = new SystemUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SystemUserRecord> getRecordType() {
        return SystemUserRecord.class;
    }

    /**
     * The column <code>public.system_user.id</code>.
     */
    public final TableField<SystemUserRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.system_user.name</code>.
     */
    public final TableField<SystemUserRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.system_user.created_on</code>.
     */
    public final TableField<SystemUserRecord, OffsetDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private SystemUser(Name alias, Table<SystemUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private SystemUser(Name alias, Table<SystemUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.system_user</code> table reference
     */
    public SystemUser(String alias) {
        this(DSL.name(alias), SYSTEM_USER);
    }

    /**
     * Create an aliased <code>public.system_user</code> table reference
     */
    public SystemUser(Name alias) {
        this(alias, SYSTEM_USER);
    }

    /**
     * Create a <code>public.system_user</code> table reference
     */
    public SystemUser() {
        this(DSL.name("system_user"), null);
    }

    public <O extends Record> SystemUser(Table<O> child, ForeignKey<O, SystemUserRecord> key) {
        super(child, key, SYSTEM_USER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<SystemUserRecord, Long> getIdentity() {
        return (Identity<SystemUserRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SystemUserRecord> getPrimaryKey() {
        return Keys.SYSTEM_USER_PKEY;
    }

    @Override
    public List<UniqueKey<SystemUserRecord>> getKeys() {
        return Arrays.<UniqueKey<SystemUserRecord>>asList(Keys.SYSTEM_USER_PKEY, Keys.SYSTEM_USER_NAME_KEY);
    }

    @Override
    public SystemUser as(String alias) {
        return new SystemUser(DSL.name(alias), this);
    }

    @Override
    public SystemUser as(Name alias) {
        return new SystemUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemUser rename(String name) {
        return new SystemUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemUser rename(Name name) {
        return new SystemUser(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, OffsetDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
