/*
 * This file is generated by jOOQ.
 */
package com.example.yourtubebackend.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.system_user_id_seq</code>
     */
    public static final Sequence<Long> SYSTEM_USER_ID_SEQ = Internal.createSequence("system_user_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.video_id_seq</code>
     */
    public static final Sequence<Long> VIDEO_ID_SEQ = Internal.createSequence("video_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
