/*
 * This file is generated by jOOQ.
 */
package com.example.yourtubebackend.jooq;


import com.example.yourtubebackend.jooq.tables.SystemUser;
import com.example.yourtubebackend.jooq.tables.Video;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.system_user</code>.
     */
    public static final SystemUser SYSTEM_USER = SystemUser.SYSTEM_USER;

    /**
     * The table <code>public.video</code>.
     */
    public static final Video VIDEO = Video.VIDEO;
}
